# Generated by Django 3.0 on 2022-03-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donneurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='code')),
                ('nni', models.IntegerField(verbose_name='Numero National Indentification')),
                ('nom_du_donneur', models.CharField(max_length=100, verbose_name='NOM DU DONNEUR')),
                ('prenom_d', models.CharField(max_length=3, verbose_name='PRENOM')),
                ('adresse', models.CharField(max_length=15, verbose_name='ADRESSE')),
                ('date_prelevement', models.DateField(verbose_name='Date de Prelevement')),
                ('lieu_de_prelevement', models.CharField(max_length=120, verbose_name='Lieu de Prelevement')),
                ('genre_donneur', models.CharField(max_length=120, verbose_name='GENRE')),
                ('groupe_sanguin', models.CharField(max_length=125, verbose_name='GROUPE SANGUIN')),
                ('rhesus_donneur', models.CharField(max_length=115, verbose_name='RHESUS')),
                ('quantité', models.CharField(max_length=85, verbose_name='QUANTITÉ')),
            ],
        ),
    ]
